# Generated by Django 2.2.9 on 2020-03-13 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_goods_num', models.IntegerField(default=1, verbose_name='商品总数')),
                ('c_is_select', models.BooleanField(default=True, verbose_name='商品是否选中')),
            ],
            options={
                'db_table': 'chuan_cart',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_price', models.FloatField(default=0, verbose_name='订单价格')),
                ('o_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('o_status', models.IntegerField(default='1', verbose_name='订单状态')),
                ('o_merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.Merchant', verbose_name='商家ID')),
            ],
            options={
                'db_table': 'chuan_order',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_goods_num', models.IntegerField(default=1, verbose_name='商品数量')),
                ('o_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.Goods', verbose_name='订单商品')),
                ('o_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='订单ID')),
            ],
            options={
                'db_table': 'chuan_orderGoods',
            },
        ),
    ]
