# Generated by Django 2.2.9 on 2020-02-19 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('merchant', '0002_goods_project'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_price', models.FloatField(default=0, verbose_name='订单价格')),
                ('o_time', models.DateTimeField(auto_now=True, verbose_name='下单时间')),
                ('o_status', models.IntegerField(default=1, verbose_name='订单状态')),
                ('o_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users', verbose_name='用户ID')),
            ],
            options={
                'db_table': 'chuan_order',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_goods_num', models.IntegerField(default=1, verbose_name='商品数量')),
                ('o_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.Goods', verbose_name='订单商品')),
                ('o_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='订单ID')),
            ],
            options={
                'db_table': 'chuan_orderGoods',
            },
        ),
    ]
