# Generated by Django 2.2.9 on 2020-02-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_merchantName', models.CharField(max_length=32, unique=True, verbose_name='商家名')),
                ('m_password', models.CharField(max_length=256, verbose_name='商家密码')),
                ('m_phone', models.CharField(max_length=13, unique=True, verbose_name='商家手机号')),
                ('m_email', models.CharField(max_length=64, unique=True, verbose_name='商家邮箱号')),
                ('m_icon', models.ImageField(upload_to='photo/%Y/%m/%d', verbose_name='商家头像')),
                ('m_idCard', models.CharField(max_length=18, unique=True, verbose_name='商家身份证')),
                ('m_idCard_front', models.ImageField(upload_to='photo/%Y/%m/%d', verbose_name='商家身份证正面照')),
                ('m_idCard_back', models.ImageField(upload_to='photo/%Y/%m/%d', verbose_name='商家身份证背面照')),
                ('is_active', models.BooleanField(default=False, verbose_name='商家激活状态')),
                ('is_delete', models.BooleanField(default=False, verbose_name='商家是否删除')),
            ],
            options={
                'db_table': 'chuan_merchant',
            },
        ),
    ]
