# Generated by Django 2.2.9 on 2020-02-17 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField(max_length=32, verbose_name='项目名称')),
                ('p_introText', models.TextField(verbose_name='项目简介')),
                ('p_classify', models.CharField(max_length=16, verbose_name='项目分类')),
                ('p_introImg', models.ImageField(upload_to='project/%Y/%m/%d', verbose_name='简介图片')),
                ('p_detail', models.ImageField(upload_to='project/%Y/%m/%d', verbose_name='详细图片')),
                ('p_days', models.IntegerField(default=30, verbose_name='众筹期限')),
                ('p_follow', models.IntegerField(default=0, verbose_name='关注数')),
                ('p_target', models.IntegerField(verbose_name='目标金额')),
                ('p_already', models.IntegerField(default=0, verbose_name='已筹金额')),
                ('p_status', models.CharField(choices=[('readyto', '即将开始'), ('funding', '众筹中'), ('success', '众筹成功'), ('failed', '众筹失败')], default='readyto', max_length=20, verbose_name='项目状态')),
                ('p_merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.Merchant', verbose_name='商家ID')),
            ],
            options={
                'db_table': 'chuan_project',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_title', models.CharField(max_length=32, verbose_name='商品名称')),
                ('g_img', models.ImageField(upload_to='project/%Y/%m/%d', verbose_name='商品图片')),
                ('g_detail', models.TextField(verbose_name='商品详细')),
                ('g_price', models.IntegerField(verbose_name='商品价格')),
                ('g_sold', models.IntegerField(default=0, verbose_name='商品已定数量')),
                ('g_stock', models.IntegerField(default=99999999, verbose_name='商品库存')),
                ('g_postage', models.IntegerField(default=0, verbose_name='配送费')),
                ('g_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.Project', verbose_name='商品项目')),
            ],
            options={
                'db_table': 'chuan_goods',
            },
        ),
    ]
