# Generated by Django 2.2.9 on 2020-02-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('u_password', models.CharField(max_length=256, verbose_name='用户密码')),
                ('u_email', models.CharField(max_length=64, unique=True, verbose_name='用户邮箱')),
                ('u_icon', models.ImageField(upload_to='icons/%Y/%m/%d', verbose_name='用户头像')),
                ('is_active', models.BooleanField(default=False, verbose_name='用户激活状态')),
                ('is_delete', models.BooleanField(default=False, verbose_name='用户是否删除')),
            ],
            options={
                'db_table': 'chuan_user',
            },
        ),
    ]
