# Generated by Django 2.2.9 on 2020-02-23 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_ordergoods'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=16, verbose_name='收货姓名')),
                ('a_phone', models.CharField(max_length=11, verbose_name='收货手机号码')),
                ('a_address', models.CharField(max_length=256, verbose_name='收货地址')),
                ('a_code', models.CharField(max_length=6, null=True, verbose_name='邮政编码')),
                ('a_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='订单ID')),
            ],
            options={
                'db_table': 'chuan_addressCopy',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=16, verbose_name='收货姓名')),
                ('a_phone', models.CharField(max_length=11, verbose_name='收货手机号码')),
                ('a_address', models.CharField(max_length=256, verbose_name='收货地址')),
                ('a_code', models.CharField(max_length=6, verbose_name='邮政编码')),
                ('a_is_default', models.BooleanField(default=True, verbose_name='默认地址')),
                ('a_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users', verbose_name='用户ID')),
            ],
            options={
                'db_table': 'chuan_address',
            },
        ),
    ]
